version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: aws-glue-assets-640958509818-us-east-1
    ARTIFACT_PREFIX: scripts

phases:
  build:
    commands:
      - echo "Uploading Glue script to artifact bucket..."
      - aws s3 cp glue_etl.py s3://$ARTIFACT_BUCKET/$ARTIFACT_PREFIX/my-glue-job.py


